### ISSUE TITLE
اخى فى الله كنت احاول تهكير جميل واحد صاحبى معرفتش

### ISSUE THREAD

**Issue by knassar702** [DEMON1A/GmailBruterV1.1#1]
هاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهاهارر

# رد يا مهنج

**Comment by knassar702** [comment]
تم الدعس من قبل هكر الفتيان الشيعى

**Comment by knassar702** [comment]
راقب حسابك

**Comment by knassar702** [comment]
هنجتك

**Comment by knassar702** [comment]
نحن من نكتب [ الروآيآت]


ونحن منندعس [ الحمآيآت ]


فإن رأيت الحمآيآت [ خآضعه ]


وممرآتالسيرفرآت [ هآدئه ]


فعلم أن الوقت قد [ حآن ]


وسترى مآليس [ بالحسبآن ]


وستتأكد أن فريقك الأمني قد وقعوآ فــي ( مزبلة التآريخ )


(المدني بالحبال والجندي بالرصاص والتهكير للعباقرة )
صاحب السيرفر ، تعجبني ثقتك بالحماية

لا حدود للمعرفة لا حدود للاختراق لا حدود للاحتراف
مهما تعبت ودفعت ، تأكد ما فيه حماية الا تخترق !
اسف ، كل الاسف .. الانترنت لعبة لا يجيدها الا من صنعها :D




نحن لاندعي الذكآء.!


ولكن نسعى..

لتحطيم الاذكيآ



للتهور جنون وللقيادة فنون وللتهكير رجل مجنون

ســنعيـش صـقـورا طائـريـنو سـنموت اسـودا شـامخيـن

وراء كل ابتسامة هكر .. دمعة ضحيه!
نعشق الموت ولا نعشق الضعفاء فدخلنا مدارس الهكر لنعاقب الحقراء !
لا نعرف الرحمه ولا نرضى بالتهديد لك حرية التعبير ولنا حرية التهكير !
نحن لا نخترق لكي نثبت اننا محترفون بل لنضع بصمة في تاريخك الاسود !!
نحن لن نستسلم نخترق او نموت !

هوايتي (الهاكر)...وهدفي (الاحتراف)... عمري غير مهم لأني كلما أكبر أميل الى(الفناء)...أريد تركـ بصمتي لكنها (ممحية)

عندما نمر فلترفع الايدي وليضرب لنا السلام


وراء كل ابتسامة هكر .. دمعة ضحية


نعشق الموت لكي لا تعشقنا الحياة فدخلنا مدارس الهكر لنعاقب الحقراء

لا نعرف الرحمه ولا نرضى بالتهديد لك حرية التعبير ولي حرية التهكير

نحن لا نخترق لكي نثبت اننا محترفون بل نضع بصمة في تاريخك

**Comment by knassar702** [comment]
we are anonymous

**Comment by Generalsony** [comment]
كسمك اولانى كسمك تانى كسمك المانى كسمك حلوانى كسمك تيوانى كسمك نيكتو قال عايز تاني كسمك مجانى ابن علوق كسمه مزنوق كسمك مخنوق كسمك مخروق كسمك ملبس كسمك اتدبس زبى فى طيزك ياعار كسمك مولع نار كسمك دخل فى حمار كسمك محتار كسمك عطار كسمك غدار كسمك جردل كسمك خردل كسمك جراح كسمك مفتاح كسمك فلاح كسمك انانى كسمك سودانى كسمك عنوانى كسمك مكانى كسمك نكيتو قال اه ياني كسمك متين طلع بنزين كسمك طلع تخين نيكتو بزبى السمين كسمك من زبى اتجن كسمك على زبى حن كسمك مخفور كسمك من زبي منطور كسمك جربوع كسمك ملسوع كسمك مصاصه كسمك استيكه وكراسه كسمك بالطول بنيكه عالطول واخدها بالعرض وبالطول امك منيوكه امك زانيوكه كسمك فى الحاره كسمك فى غاره كسمك فى سيجاره كسمك فى طياره كسمك فى خياره كسمك قاعد على المناره كسمك صناره كسمك فقعلى المراره كسمك فتاكة نكته بزبي بشياكة كسمك فتّاق كسمك حراق كسمك شفته من الشباك كسمك حشاش كسمك قشاش كسمك ببلاش كسمك قطران كسمك حران كسمك بودان كسمك بردان كسمك تعبان كسمك حزين دخل فيه زبين كسمك طويل نيكتو في شقة على النيل

**Comment by knassar702** [comment]
ههههههههههههههههههههه مهنجتنيش عشان انا هكر جامد

**Comment by DEMON1A** [comment]
First of all fuck off

**Comment by DEMON1A** [comment]
تاني حاجه روح خدلك كورس لاوامر اللينكس عشان تعرف تشغل الاداه الاول ههههههههههه
